ProjectX/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^oauth/', include('oauth.urls')),
    #url(r'^dashboard/', include('dashboard.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

oauth/urls.py
from django.conf.urls import url
from oauth import views

app_name = 'oauth'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register/', views.CustomerFormView.as_view(), name='register'),
]

dashboard/models.py
from django.db import models

# Create your models here.

oauth/models.py
from django.db import models
from django.core.validators import RegexValidator
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager, User, Group


# Create your models here.

class AuthUserManager(BaseUserManager):
    def create_user(self, username, email, password=None):
        if not email:
            raise ValueError('Users must have an email address')
        if not username:
            raise ValueError('Users must have a phone number')
        if not password:
            raise ValueError('Password cannot be left')

        user = self.model(username=username, email=self.normalize_email(email), )
        user.is_active = True
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, email, password):
        user = self.create_user(username=username, email=email, password=password)
        user.is_staff = True
        user.is_superuser = True
        user.set_password(password)
        user.save(using=self._db)
        return user


class Customer(AbstractBaseUser, PermissionsMixin):
    alphanumeric = RegexValidator(r'^[0-9a-zA-Z]*$', message='Only alphanumeric characters are allowed.')
    numeric = RegexValidator(r'^[0-9]*$', message='Not a valid number!')
    # Redefine the basic fields that would normally be defined in User
    username = models.CharField(unique=True, max_length=10, validators=[numeric])
    email = models.EmailField(verbose_name='email address', unique=True, max_length=255)
    first_name = models.CharField(max_length=30, null=True, blank=True)
    last_name = models.CharField(max_length=50, null=True, blank=True)
    roll = models.CharField(max_length=20, null=False, blank=False)
    date_joined = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True, null=False)
    is_staff = models.BooleanField(default=False, null=False)
    balance = models.IntegerField(default=0)
    # Our own fields
    profileImage = models.ImageField(upload_to="avatar")
    objects = AuthUserManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    def get_full_name(self):
        fullname = str(self.first_name) + " " + str(self.last_name)
        return fullname

    def get_short_name(self):
        return self.first_name

    def __unicode__(self):
        return self.username

oauth/forms.py
from django import forms
from oauth.models import Customer


class CustomerForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = Customer
        fields = ['username', 'email', 'password']

dashboard/views.py
from django.shortcuts import render

# Create your views here.

oauth/views.py
from django.shortcuts import render, redirect
# from django.contrib.auth import authenticate, login
from django.views.generic import View
from .forms import CustomerForm


def index(request):
    return render(request, 'oauth/index.html')


class CustomerFormView(View):
    form_class = CustomerForm
    template_name = 'oauth/register.html'

    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form, 'error_message': False})

    def post(self, request):
        form = self.form_class(request.POST)

        def pass_match():
            password = form.cleaned_data['password']
            password2 = request.POST['verifypass']
            if password == password2:
                return True
            else:
                return False

        if form.is_valid() and pass_match():
            user = form.save(commit=False)
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()
            return redirect('oauth:index')

        elif not pass_match():
            return render(request, self.template_name, {'form': form,  'error_message': True})

        return render(request, self.template_name, {'form': form})

oauth/templates/oauth/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %} ProjectX {%  endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'oauth/css/bootstrap.css' %}" rel="stylesheet">

    <!-- Material Design Bootstrap -->
    <link href="{% static 'oauth/css/mdb.min.css' %}" rel="stylesheet">

    <!-- Font Awesome -->
    <script src="https://use.fontawesome.com/63e2ad3e7c.js"></script>

{% block custom_styles %}
{% endblock %}

</head>
<body>
{% block navbar %}
    <!--Navbar-->
    <nav class="navbar navbar-toggleable-md navbar-dark fixed-top scrolling-navbar">
        <div class="container">
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNav1" aria-controls="navbarNav1" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <a class="navbar-brand" href="#">
                <strong>IITJ</strong>
            </a>
            <div class="collapse navbar-collapse" id="navbarNav1">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link">Home <span class="sr-only">(current)</span></a>
                    <li class="nav-item">
                        <a class="nav-link">About</a>
                    </li>
                </ul>
                <form class="form-inline waves-effect waves-light">
                    <input class="form-control" type="text" placeholder="Search">
                </form>
            </div>
        </div>
    </nav>
    <!--/.Navbar-->
{%  endblock %}


{% block body %}
{% endblock %}


{% block scripts %}
    <!-- SCRIPTS -->

    <!-- JQuery -->
    <script type="text/javascript" src="{% static 'oauth/js/jquery-3.1.1.js' %}"></script>

    <!-- Bootstrap tooltips -->
    <script type="text/javascript" src="{% static 'oauth/js/tether.js' %}"></script>

    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript" src="{% static 'oauth/js/bootstrap.js' %}"></script>

    <!-- MDB core JavaScript -->
    <script type="text/javascript" src="{% static 'oauth/js/mdb.js' %}"></script>

{% endblock %}

</body>
</html>

oauth/templates/oauth/index.html
{% extends 'oauth/base.html' %}
{% block custom_styles %}
    <!-- Template styles -->
    <style rel="stylesheet">
        /* TEMPLATE STYLES */
        
        html,
        body,
        .view {
            height: 100%;
        }
        /* Navigation*/
        
        .navbar {
            background-color: transparent;
        }
        
        .scrolling-navbar {
            -webkit-transition: background .5s ease-in-out, padding .5s ease-in-out;
            -moz-transition: background .5s ease-in-out, padding .5s ease-in-out;
            transition: background .5s ease-in-out, padding .5s ease-in-out;
        }
        
        .top-nav-collapse {
            background-color: #1C2331;
        }
        
        footer.page-footer {
            background-color: #1C2331;
            margin-top: -1px;
        }
        
        @media only screen and (max-width: 768px) {
            .navbar {
                background-color: #1C2331;
            }
        }
        /*Call to action*/
        
        .flex-center {
            color: #fff;
        }
        
        .view {
            background: url("http://mdbootstrap.com/img/Photos/Horizontal/City/full%20page/img%20(1).jpg")no-repeat center center fixed;
            -webkit-background-size: cover;
            -moz-background-size: cover;
            -o-background-size: cover;
            background-size: cover;
        }
    </style>
{% endblock %}


{% block body %}
    <!--Mask-->
    <div class="view hm-black-strong">
        <div class="full-bg-img flex-center">
            <ul class="animated fadeInUp">
                <li>
                    <h1 class="h1-responsive">Project X</h1></li>
                <li>
                    <p>Wireless.Centralised.Secured</p>
                </li>
                <li>
                    <a href="http://mdbootstrap.com/getting-started/" class="btn btn-primary btn-lg">Login</a>
                    <a href="{% url 'oauth:register' %}" class="btn btn-default btn-lg">Register Now</a>
                </li>
            </ul>
        </div>
    </div>
{% endblock %}

oauth/templates/oauth/register.html
{% extends 'oauth/base.html' %}
{% block title %} Register New User {% endblock %}
{% block navbar %}
    <!--Navbar-->
    <nav class="navbar navbar-toggleable-md navbar-light fixed-top scrolling-navbar">
        <div class="container">
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNav1" aria-controls="navbarNav1" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <a class="navbar-brand" href="#">
                <strong>IITJ</strong>
            </a>
            <div class="collapse navbar-collapse" id="navbarNav1">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link">Home <span class="sr-only">(current)</span></a>
                    <li class="nav-item">
                        <a class="nav-link">About</a>
                    </li>
                </ul>
                <form class="form-inline waves-effect waves-light">
                    <input class="form-control" type="text" placeholder="Search">
                </form>
            </div>
        </div>
    </nav>
    <!--/.Navbar-->
{% endblock %}

{% block body %}
    <div class="container">
        <div style="margin-top: 7em;"></div>
        <div class="row">
            <div class="col-md-6 col-lg-5 login-form mx-auto float-none">
                <!--Form with header-->
                <div class="card">
                    <div class="card-block">
                        <form action="" method="post">
                        {% csrf_token %}
                            <!--Header-->
                            <div class="form-header blue">
                                <h3><i class="fa fa-user"></i> Register:</h3>
                            </div>
                            {% if error_message %}
                                <div class="red-text"><p>Password doesn't match</p></div>
                            {% endif %}

                            <!--Body-->
                            <div class="md-form">
                                <i class="fa fa-phone prefix"></i>
                                <input type="text" id="username" name="username" class="form-control">
                                <label for="usernames">Phone as username</label>
                            </div>
                            <div class="md-form">
                                <i class="fa fa-user prefix"></i>
                                <input type="text" id="first_name" name="first_name" class="form-control">
                                <label for="first_name">First name</label>
                            </div>
                            <div class="md-form">
                                <i class="prefix"></i>
                                <input type="text" id="last_name" name="last_name" class="form-control">
                                <label for="last_name">Last name</label>
                            </div>
                            <div class="md-form">
                                <i class="fa fa-envelope prefix"></i>
                                <input type="text" id="email" name="email" class="form-control">
                                <label for="email">Email</label>
                            </div>
                            <div class="md-form">
                                <i class="fa fa-phone prefix"></i>
                                <input type="text" id="phone" name="phone" class="form-control">
                                <label for="phone">Phone</label>
                            </div>
                            <div class="md-form">
                                <i class="fa fa-lock prefix"></i>
                                <input type="password" id="password" name="password" class="form-control">
                                <label for="password">Password</label>
                            </div>

                            <div class="md-form">
                                <i class="prefix"></i>
                                <input type="password" id="verifypass" name="verifypass" class="form-control">
                                <label for="verifypass">Type password again</label>
                            </div>

                            <div class="text-center">
                                <button class="btn blue" type="submit">Register</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    <!--/Form with header-->
    </div>
{% endblock %}